apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ops-platform-prometheus
  labels:
    app: prometheus
    component: observability
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - nodes/metrics
    verbs:
      - get

  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get