apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: ops-platform
  labels:
    app: node-exporter
    component: observability
spec:
  selector:
    matchLabels:
      app: node-exporter

  template:
    metadata:
      labels:
        app: node-exporter
        component: observability

    spec:
      hostNetwork: true
      hostPID: true

      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.11.1
          imagePullPolicy: IfNotPresent

          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            - --web.listen-address=:9100
            - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)

          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
              protocol: TCP

          startupProbe:
            tcpSocket:
              port: metrics
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: metrics
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true

            - name: sys
              mountPath: /host/sys
              readOnly: true

            - name: root
              mountPath: /host/root
              readOnly: true
              mountPropagation: HostToContainer

      volumes:
        - name: proc
          hostPath:
            path: /proc
            type: Directory

        - name: sys
          hostPath:
            path: /sys
            type: Directory

        - name: root
          hostPath:
            path: /
            type: Directory
