apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: ops-platform
  labels:
    app: blackbox-exporter
    component: observability
spec:
  type: ClusterIP

  selector:
    app: blackbox-exporter

  ports:
    - name: http
      port: 9115
      targetPort: http
      protocol: TCP
