apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: ops-platform
  labels:
    app: auth-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: visualbinary/ops-platform-auth-service:local
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8000

          env:
            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: ops-platform-config
                  key: JWT_ALGORITHM

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ops-platform-secret
                  key: JWT_SECRET_KEY

          startupProbe:
            httpGet:
              path: /health/startup
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: auth-data
              mountPath: /app/data

      volumes:
        - name: auth-data
          persistentVolumeClaim:
            claimName: auth-data