apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: auth-data
  namespace: ops-platform
  labels:
    app: auth-service

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi