global:
  scrape_interval: 15s

rule_files:
  - prometheus-alerts.yml

scrape_configs:
  - job_name: "asset-service"
    static_configs:
      - targets: ["asset_service:8000"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth_service:8000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]