apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: ops-platform
  labels:
    app: loki
    component: observability
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      path_prefix: /var/loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index-cache
      filesystem:
        directory: /var/loki/chunks

    compactor:
      working_directory: /var/loki/compactor
      retention_enabled: true
      delete_request_store: filesystem

    limits_config:
      retention_period: 168h
      allow_structured_metadata: true

    analytics:
      reporting_enabled: false
