apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: ops-platform
  labels:
    app: loki
    component: observability
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
