apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: ops-platform
  labels:
    app: alloy
    component: observability
spec:
  type: ClusterIP

  selector:
    app: alloy

  ports:
    - name: http
      port: 12345
      targetPort: http
      protocol: TCP
